name: Publish Any Commit

on:
  pull_request:
    branches: main
    paths-ignore:
      - 'docs/**'
      - 'playground/**'
      - 'packages/nuxt/playground/**'

  push:
    branches:
      - '**'
    tags:
      - '!**'
    paths-ignore:
      - 'docs/**'
      - 'playground/**'
      - 'packages/nuxt/playground/**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Prepare Nuxt
        run: pnpm -C ./nuxt dev:prepare

      - name: Build
        run: pnpm build

      - name: Build plugins
        run: pnpm build:plugins

      - name: Release
        run: pnpm dlx pkg-pr-new@https://bd9ae1c9.stackblitz-cr.pages.dev/stackblitz-labs/pkg.pr.new/pkg-pr-new@266 publish --compact --pnpm . './plugins/*' ./nuxt
